# OpenAI settings
OPENAI_MODEL = "gpt-5"
OPENAI_TIMEOUT = 30.0

# When the overall rule-based confidence falls below this threshold, call the LLM.
LLM_CONFIDENCE_THRESHOLD = 0.70

# Rule-based per-field confidence values
TRACKING_MIN_LENGTH = 15
CONFIDENCE_TRACKING_HIGH = 0.95
CONFIDENCE_TRACKING_LOW = 0.40
CONFIDENCE_NAME_HIGH = 0.85
CONFIDENCE_NAME_LOW = 0.45
CONFIDENCE_STREET_HIGH = 0.85
CONFIDENCE_STREET_LOW = 0.45
CONFIDENCE_CITY_HIGH = 0.85
CONFIDENCE_CITY_LOW = 0.45
CONFIDENCE_STATE_VALID = 0.95
CONFIDENCE_ZIP_VALID = 0.95

# LLM cross-validation against OCR text
CONFIDENCE_LLM_OCR_MATCH = 0.85
CONFIDENCE_LLM_OCR_MISMATCH = 0.30

# SQLite storage
STORAGE_DB_PATH = "label_storage.db"

# Camera label detection
CAMERA_MIN_AREA_RATIO = 0.10
CAMERA_STABLE_SECONDS = 2.0
CAMERA_HISTORY_FRAMES = 10
CAMERA_HISTORY_THRESHOLD = 3
